name: kuleta
description: Lekë management app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.6

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.5
  flex_color_scheme: ^6.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  go_router: ^5.1.6
  google_fonts: ^3.0.1
  group_list_view: ^1.1.1
  # command used to install `mobile_scanner` on ios:
  # https://github.com/CocoaPods/CocoaPods/issues/10287#issuecomment-902354887
  intl: ^0.17.0
  invoice_repository:
    path: packages/invoice_repository
  mobile_scanner: ^2.0.0
  provider: ^6.0.4

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
